const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generateCertificate = (data) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                layout: 'landscape',
                size: 'A4',
            });

            const { userName, eventName, date } = data;
            const filename = `certificate_${userName.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
            const filePath = path.join(__dirname, '../utils/temp', filename);

            // Ensure temp directory exists
            if (!fs.existsSync(path.join(__dirname, '../utils/temp'))) {
                fs.mkdirSync(path.join(__dirname, '../utils/temp'), { recursive: true });
            }

            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            // Design
            doc.rect(20, 20, doc.page.width - 40, doc.page.height - 40).stroke();
            
            doc.fontSize(40).text('CERTIFICATE OF PARTICIPATION', { align: 'center' }).moveDown();
            doc.fontSize(20).text('This is to certify that', { align: 'center' }).moveDown();
            doc.fontSize(30).text(userName, { align: 'center', underline: true }).moveDown();
            doc.fontSize(20).text(`has successfully participated in the event`, { align: 'center' }).moveDown();
            doc.fontSize(25).text(eventName, { align: 'center' }).moveDown();
            doc.fontSize(15).text(`Held on: ${new Date(date).toLocaleDateString()}`, { align: 'center' }).moveDown();
            
            doc.fontSize(10).text('Generated by Event Management System', { align: 'center', baseline: 'bottom' });

            doc.end();

            stream.on('finish', () => {
                resolve(filePath);
            });
            stream.on('error', (err) => {
                reject(err);
            });
        } catch (error) {
            reject(error);
        }
    });
};

module.exports = { generateCertificate };
